### ISSUE TITLE
第一次运行不行，第二次才可以

### ISSUE THREAD

**Issue by iamsad3508** [lvwzhen/Ask2End#7]
ubuntu gitclone项目 ，然后补了.env进去，运行npm run dev就出现错误
![Screenshot_20230512-201516_1](https://github.com/lvwzhen/Ask2End/assets/3872185/5baa24bc-9bff-4d5f-b402-dad0382a391c)

![Screenshot_20230512-201553](https://github.com/lvwzhen/Ask2End/assets/3872185/3739a590-189e-4062-9654-c2a667c00743)
![Screenshot_20230512-201530](https://github.com/lvwzhen/Ask2End/assets/3872185/616d6b70-454b-4d80-9058-9aa64cbeb75c)
ctrl+c结束进程后，再运行一次，才能访问
![Screenshot_20230512-202646](https://github.com/lvwzhen/Ask2End/assets/3872185/5fb0d75e-22ff-46ad-8987-cf5291029893)

**Comment by lvwzhen** [comment]
需要部署在vercel中
